### PR TITLE
Update plugin with latest core

### PR DESCRIPTION
**Pull request by cocoataster**
Partially remove exposure to Research Kit with latest core changes.

WIP - Titles are duplicated, since we have Large Titles and `MWInstructionStepViewController` still sets a title. Maybe we could remove `titleLabe` from `configureWithTitle` func?

### CODE REVIEW

**Comment by cocoataster** [comment]
@FWJonathan made some changes to update this Plugin, since we were trying to test Notifications from BE on Signature 😄  I'll be back on Tuesday and will continue with this, but just to give you a heads up regarding title duplication here 🤓 
IMG_FE28B6FC6A0E-1

**Comment by FWJonathan** [comment]
YeH, I'm in the process of fixing this in the core.

**Comment by FWJonathan** [comment]
I also started updating this plugin. Will have it updated today, either using this branch or my branch.

**Comment by FWJonathan** [comment]
@cocoataster Thanks for doing this, but closing as duplicate of my PR: https://github.com/FutureWorkshops/MWPushNotificationsPlugin-iOS/pull/4

**Pull request closed without merging**
